- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'hi, this is from command module' > /tmp/command.txt"

  - name: shell module
    ansible.builtin.shell: "echo 'hi, this is from shell module' > /tmp/shell.txt "
    
