- name: variables
  hosts: localhost
  vars:
   course: "ansible"
   trainer: "kumar"
   duration: "20hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
     msg: "hi i m learning {{course}} from {{trainer}},duration is {{duration}}."